### ISSUE TITLE
qgis3 port

### ISSUE THREAD

**Issue by vincentschut** [mach0/mutant#8]
Hi, I've made a qgis3 version of Mutant. If you are interested I can make a PR. Just let me know :-)

The port is probably quite rough, as I am not an experienced qgis python plugin developer, but it seems to be working fine with my local qgis3 build.

You can find the repo here: https://github.com/vincentschut/mutant, the port is in the 2to3 branch.

**Comment by mach0** [comment]
Great! Sure - you are more than welcome to do a pull request.
I did not migrate to 3 until now because lack of time. So your contribution is more than welcome.
If you want I can do an experimental release for 3.0 (of course with credits to you).
My current approach on releasing plugins is to name the version for QGIS 2.x also 2.x and to do the development for QGIS 3.0 in master (and releasing them also with a 3.x version number).
Until QGIS 4.0 is coming ;)

**Comment by vincentschut** [comment]
Perfect. I'll create a PR then, and we can continue to discuss things there.
